#!/usr/bin/env bash
# Start a single ADK agent. Requires AGENT_NAME and PORT.
set -e
AGENT_NAME="${AGENT_NAME:?AGENT_NAME is required}"
PORT="${PORT:?PORT is required}"
PROJECT_ROOT="/app"
AGENT_WORK="${PROJECT_ROOT}/agent_work"
mkdir -p "$AGENT_WORK"
# Copy agent into agent_work so resolved path stays inside (ADK rejects symlinks that resolve outside)
cp -r "${PROJECT_ROOT}/agents/${AGENT_NAME}" "${AGENT_WORK}/${AGENT_NAME}"
# Orchestrator: also expose as threat_model_orchestrator so server can use that app name
if [[ "$AGENT_NAME" == "orchestrator" ]]; then
  cp -r "${PROJECT_ROOT}/agents/orchestrator" "${AGENT_WORK}/threat_model_orchestrator"
fi

WRAPPER_FILE="${PROJECT_ROOT}/app/_agent_wrapper_${AGENT_NAME}.py"
# Orchestrator uses a2a=False; others use a2a=True
A2A="True"
[[ "$AGENT_NAME" == "orchestrator" ]] && A2A="False"

cat > "$WRAPPER_FILE" << PYCODE
"""
Temporary wrapper module to start a single ADK agent as a FastAPI app.
Auto-generated by agents/entrypoint.sh
"""
import sys
import logging
from pathlib import Path

project_root = Path("${PROJECT_ROOT}")
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

logging.getLogger("opentelemetry.attributes").setLevel(logging.ERROR)

from google.adk.cli import fast_api
from starlette.middleware.base import BaseHTTPMiddleware

agents_parent = Path("${AGENT_WORK}")
app = fast_api.get_fast_api_app(
    agents_dir=str(agents_parent),
    session_service_uri=None,
    artifact_service_uri=None,
    memory_service_uri=None,
    eval_storage_uri=None,
    allow_origins=[],
    web=False,
    trace_to_cloud=False,
    otel_to_cloud=False,
    a2a=${A2A},
    host="0.0.0.0",
    port=${PORT},
    url_prefix=None,
    reload_agents=False,
    extra_plugins=None,
)

try:
    from shared.tools.a2a_utils import a2a_card_middleware
    app.add_middleware(BaseHTTPMiddleware, dispatch=a2a_card_middleware)
except ImportError:
    pass
PYCODE

# All agents: add set-api-key so server can set API key / Vertex / model from frontend (ADK uses env)
cat >> "$WRAPPER_FILE" << 'PYCODE2'
import os
from fastapi import Request
@app.post("/set-api-key")
async def set_api_key(request: Request):
    body = await request.json()
    api_key = (body.get("api_key") or "").strip()
    if api_key:
        os.environ["GOOGLE_API_KEY"] = api_key
    if body.get("use_vertex"):
        os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"
        if body.get("vertex_project"):
            os.environ["GOOGLE_CLOUD_PROJECT"] = body["vertex_project"]
        if body.get("vertex_location"):
            os.environ["GOOGLE_CLOUD_LOCATION"] = body["vertex_location"]
    model_id = (body.get("model_id") or "").strip()
    if model_id:
        os.environ["GOOGLE_GENAI_MODEL"] = model_id
    return {"ok": True}
PYCODE2

cd "$PROJECT_ROOT"
export PYTHONPATH="$PROJECT_ROOT"
export ADK_SUPPRESS_EXPERIMENTAL_FEATURE_WARNINGS="True"
exec uv run uvicorn "app._agent_wrapper_${AGENT_NAME}:app" --host 0.0.0.0 --port "$PORT"
